name: Matlab Docker 2023b
language: python
variables:
  - name: input
    inputType: InputTopic
    multiline: false
    description: This is the raw data input topic
    defaultValue: 2d-vector
    required: true
  - name: output
    inputType: OutputTopic
    multiline: false
    defaultValue: matlab-docker-2023b
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
